FROM docker.io/nginx:1.23-alpine

COPY out/index.html /usr/share/nginx/html/index.html
COPY out/config.json /usr/share/nginx/html/config.json
COPY out/bundle/main.js /usr/share/nginx/html/bundle/main.js