/* eslint-disable camelcase */
/**
 * This is a machine translation and may have some mistakes.
 *
 * If you have a more accurate translation for any of these strings, please open an issue or pull request.
 */
export const I18N_STRINGS_DE = {
  de: {
    translation: {
      admin: {
        restart: 'Arbeiter neu starten',
      },
      convert: 'Speichern und konvertieren',
      error: {
        image: {
          csam: '',
          memory: '',
          oom: '',
          unknown: '',
        },
        inpaint: {
          support: 'Dieses Modell unterstützt möglicherweise keine Bearbeitung.',
        },
      },
      extras: {
        add: 'Artikel hinzufügen',
        dest: 'Ordnernamen',
        format: 'Datei Format',
        label: 'Etikett',
        model: 'Modell',
        name: 'Name',
        remove: 'Entfernen',
        scale: 'Skala',
        source: 'Ursprung',
        type: 'Typ',
      },
      generate: 'Erzeugen',
      profile: {
        add: 'Profil hinzufügen',
        saveName: 'Profilnamen speichern',
        saveProfile: 'Profil speichern',
        save: 'Speichern',
        saveCurrent: 'Aktuelles Profil speichern',
        name: 'Name',
        cancel: 'Stornieren',
        load: 'Laden',
      },
      highresMethod: {
        bilinear: 'Bilinear',
        lanczos: 'Lanczos',
        upscale: 'Hochskalierung',
      },
      history: {
        empty: 'Keine neuere Geschichte. Drücken Sie Generieren, um ein Bild zu erstellen.',
      },
      input: {
        image: {
          empty: 'Bitte wählen Sie ein Bild aus',
          mask: 'Maskenbild',
          source: 'Quellbild',
        },
        list: {
          error: {
            specific: 'Fehler: {{message}}',
            unknown: 'unbekannter Fehler',
          },
          idle: 'Leerlauf',
          loading: 'Wird geladen',
        },
        numeric: {
          error: {
            range: 'außerhalb der Reichweite',
          },
        },
      },
      loading: {
        cancel: 'Stornieren',
        progress: '{{steps.current}} von {{steps.total}} Schritten, {{tiles.current}} of {{tiles.total}} Kacheln, {{stages.current}} of {{stages.total}} Abschnitten',
        queue: '{{current}} von {{total}} in der Warteschlange',
        server: 'Verbindung zum Server...',
        unknown: 'vielen',
      },
      mask: {
        fill: {
          black: 'Mit Schwarz füllen',
          white: 'Weiß füllen',
        },
        gray: {
          black: 'Grau in schwarz umwandeln',
          white: 'Grau in weiß umwandeln',
        },
        help: '',
        invert: 'Farben umkehren',
      },
      maskFilter: {
        'gaussian-multiply': 'Gaußsche mit Multiplikation',
        'gaussian-screen': 'Gaußsche mit Schirm',
        'none': 'Keiner',
      },
      modelType: {
        control: '',
        correction_one: 'Korrekturmodell',
        correction_other: 'Korrekturmodelle',
        diffusion_one: 'Diffusionsmodell',
        diffusion_other: 'Diffusionsmodelle',
        inversion: 'Einbettung',
        lora: 'LoRA',
        network_one: 'Extra Netzwerk',
        network_other: 'Extra Netzwerke',
        source_one: 'Andere Quelle',
        source_other: 'Andere Quellen',
        upscaling_one: 'Modell vergrößern',
        upscaling_other: 'Modelle vergrößern',
      },
      noiseSource: {
        'fill-edge': 'Kanten füllen',
        'fill-mask': 'Maskiert füllen',
        'gaussian': 'Gaußsche Unschärfe',
        'histogram': 'Histogrammrauschen',
        'normal': 'Gaußsches Rauschen',
        'uniform': 'gleichförmiges Rauschen',
      },
      parameter: {
        batch: 'Losgröße',
        brush: {
          color: 'Pinselfarbe',
          size: 'Pinselgröße',
          strength: 'Pinseldeckkraft',
        },
        cfg: 'CFG',
        eta: 'Eta',
        fillColor: 'Füllfarbe',
        height: 'Höhe',
        highres: {
          iterations: 'Iterationen',
          label: 'Hohe Auflösung',
          method: 'Methode',
          scale: 'Skala',
          steps: 'Schritte',
          strength: 'Stärke',
        },
        loopback: 'Loopback',
        lpw: 'lange prompte Gewichtung',
        maskFilter: 'Maskenfilter',
        noiseSource: 'Lärmquelle',
        negativePrompt: 'Gegenprompt',
        newSeed: 'neue Saat',
        outpaint: {
          label: 'Außenmalerei',
          left: 'Links',
          right: 'Rechts',
          top: 'Top',
          bottom: 'Unterseite',
        },
        overlap: 'Überlappung',
        pipeline: 'Pipeline',
        platform: 'Plattform',
        prompt: 'Prompt',
        scheduler: 'Planer',
        seed: 'Saat',
        size: 'Größe',
        sourceFilter: 'Quellfilter',
        steps: 'Schritte',
        strength: 'Stärke',
        tiled_vae: 'Gekachelt VAE',
        tiles: 'Kacheln',
        tileOrder: 'Reihenfolge der Kacheln',
        unet_overlap: 'UNet Überlappung',
        unet_tile: 'UNet Fliesengröße',
        upscale: {
          label: 'Gehoben',
          denoise: 'Entrauschen',
          scale: 'Skala',
          order: 'Gehobene Ordnung',
          outscale: 'Ausgangsskala',
        },
        vae_overlap: 'VAE Überlappung',
        vae_tile: 'VAE Fliesengröße',
        width: 'Breite',
        correction: {
          label: 'Gesichtskorrektur',
          strength: 'Stärke',
          outscale: 'Ausgangsskala',
        },
      },
      pipeline: {
        'none': '',
        'controlnet': '',
        'img2img': '',
        'img2img-sdxl': '',
        'inpaint': '',
        'inpaint-sdxl': '',
        'lpw': '',
        'panorama': '',
        'panorama-sdxl': '',
        'pix2pix': '',
        'txt2img': '',
        'txt2img-sdxl': '',
        'txt2txt': '',
        'upscale': '',
      },
      platform: {
        // mostly brand names, only the any platform needs to be replaced
        // eslint-disable-next-line id-blacklist
        any: 'Jede Plattform',
      },
      save: {
        image: 'Bild',
        metadata: '',
      },
      setting: {
        connectServer: 'verbinden zum Server',
        history: {
          limit: 'Länge des Bildverlaufs',
          width: 'Breite des Bildverlaufs',
        },
        prompt: 'Standard-Eingabeaufforderung',
        reset: {
          all: 'Alles zurücksetzen',
          img2img: 'Img2img zurücksetzen',
          inpaint: 'Inpaint zurücksetzen',
          txt2img: 'Txt2img zurücksetzen',
        },
        scheduler: 'Standardplaner',
        server: 'API-Server',
        state: {
          label: 'Kundenstatus',
          load: 'Laden',
          save: 'Speichern',
        },
        darkMode: 'Dunkelmodus',
      },
      sourceFilter: {
        canny: 'Canny kanten',
        depth: 'Tiefenkarte',
        face: 'Gesichtserkennung',
        gaussian: 'Gaussian verwischen',
        hed: 'HED kanten',
        mlsd: 'M-LSD bildsegmentierung',
        noise: 'Histogrammrauschen',
        none: 'Keiner',
        normal: 'normale Karte',
        openpose: 'OpenPose',
        scribble: 'Scribble',
        segment: 'Bildsegmentierung',
      },
      tab: {
        blend: 'Mischung',
        img2img: 'Img2img',
        inpaint: '',
        models: 'Modelle',
        settings: 'Einstellungen',
        txt2txt: 'Txt2txt',
        txt2img: 'Txt2img',
        upscale: 'Vergrößern',
      },
      tileOrder: {
        grid: 'Raster',
        spiral: 'Spiral',
      },
      tooltip: {
        delete: 'Löschen',
        next: 'Nächste',
        previous: 'Vorherige',
        retry: 'Neu verhandeln',
        save: 'Speichern',
      },
      upscaleOrder: {
        'correction-both': 'Korrektur bei beiden',
        'correction-first': 'Korrektur zuerst',
        'correction-last': 'Korrektur zuletzt',
      },
      wildcard: 'Wildcard',
    },
  },
};
