/* eslint-disable camelcase */
/**
 * This is a machine translation and may have some mistakes.
 *
 * If you have a more accurate translation for any of these strings, please open an issue or pull request.
 */
export const I18N_STRINGS_DE = {
  de: {
    translation: {
      admin: {
        restart: '',
      },
      convert: '',
      error: {
        image: {
          csam: '',
          memory: '',
          oom: '',
          unknown: '',
        },
        inpaint: {
          support: '',
        },
      },
      extras: {
        add: '',
        dest: '',
        format: '',
        label: '',
        model: '',
        name: '',
        remove: '',
        scale: '',
        source: '',
        type: '',
      },
      generate: 'Erzeugen',
      profile: {
        add: '',
        saveName: '',
        saveProfile: '',
        save: '',
        saveCurrent: '',
        name: '',
        cancel: '',
        load: '',
      },
      highresMethod: {
        bilinear: '',
        lanczos: '',
        upscale: '',
      },
      history: {
        empty: 'Keine neuere Geschichte. Drücken Sie Generieren, um ein Bild zu erstellen.',
      },
      input: {
        image: {
          empty: 'Bitte wählen Sie ein Bild aus',
          mask: 'Maskenbild',
          source: 'Quellbild',
        },
        list: {
          error: {
            specific: '',
            unknown: 'unbekannter Fehler',
          },
          idle: '',
          loading: '',
        },
        numeric: {
          error: {
            range: 'außerhalb der Reichweite',
          },
        },
        prompt: {
          tokens: '',
          error: {
            length: '',
          },
        },
      },
      loading: {
        cancel: 'Stornieren',
        progress: '{{current}} von {{total}} Schritten',
        queue: '',
        server: 'Verbindung zum Server...',
        unknown: 'vielen',
      },
      mask: {
        fill: {
          black: 'Mit Schwarz füllen',
          white: 'Weiß füllen',
        },
        gray: {
          black: 'Grau in schwarz umwandeln',
          white: 'Grau in weiß umwandeln',
        },
        help: '',
        invert: 'Farben umkehren',
      },
      maskFilter: {
        'gaussian-multiply': 'Gaußsche mit Multiplikation',
        'gaussian-screen': 'Gaußsche mit Schirm',
        'none': 'Keiner',
      },
      modelType: {
        control: '',
        correction_one: 'Korrekturmodelle',
        correction_other: '',
        diffusion_one: 'Diffusionsmodelle',
        diffusion_other: '',
        inversion: '',
        lora: '',
        network_one: '',
        network_other: '',
        source_one: '',
        source_other: '',
        upscaling_one: 'Modelle vergrößern',
        upscaling_other: '',
      },
      noiseSource: {
        'fill-edge': 'Kanten füllen',
        'fill-mask': 'Maskiert füllen',
        'gaussian': 'Gaußsche Unschärfe',
        'histogram': 'Histogrammrauschen',
        'normal': 'Gaußsches Rauschen',
        'uniform': 'gleichförmiges Rauschen',
      },
      parameter: {
        batch: 'Losgröße',
        brush: {
          color: 'Pinselfarbe',
          size: 'Pinselgröße',
          strength: 'Pinseldeckkraft',
        },
        cfg: '',
        eta: '',
        fillColor: 'Füllfarbe',
        height: 'Höhe',
        highres: {
          iterations: '',
          label: '',
          method: '',
          scale: '',
          steps: '',
          strength: '',
        },
        loopback: '',
        lpw: '',
        maskFilter: 'Maskenfilter',
        noiseSource: 'Lärmquelle',
        negativePrompt: 'Gegenprompt',
        newSeed: 'neue Saat',
        outpaint: {
          label: '',
          left: 'Links',
          right: 'Rechts',
          top: 'Top',
          bottom: 'Unterseite',
        },
        overlap: '',
        pipeline: '',
        platform: 'Plattform',
        prompt: 'Prompt',
        scheduler: 'Planer',
        seed: 'Saat',
        size: 'Größe',
        sourceFilter: '',
        steps: 'Schritte',
        strength: 'Stärke',
        stride: '',
        tiled_vae: '',
        tiles: '',
        tileOrder: '',
        unet_overlap: '',
        unet_tile: '',
        upscale: {
          label: '',
          denoise: 'Entrauschen',
          scale: 'Skala',
          order: '',
          outscale: 'Ausgangsskala',
        },
        vae_overlap: '',
        vae_tile: '',
        width: 'Breite',
        correction: {
          label: 'Gesichtskorrektur',
          strength: 'Stärke',
          outscale: 'Ausgangsskala',
        },
      },
      pipeline: {
        'none': '',
        'controlnet': '',
        'img2img': '',
        'img2img-sdxl': '',
        'inpaint': '',
        'inpaint-sdxl': '',
        'lpw': '',
        'panorama': '',
        'panorama-sdxl': '',
        'pix2pix': '',
        'txt2img': '',
        'txt2img-sdxl': '',
        'txt2txt': '',
        'upscale': '',
      },
      save: {
        image: '',
        metadata: '',
      },
      setting: {
        connectServer: 'verbinden zum Server',
        history: 'Bildgeschichte',
        loadState: 'Laden',
        prompt: 'Standard-Eingabeaufforderung',
        reset: {
          all: 'Alles zurücksetzen',
          img2img: 'Img2img zurücksetzen',
          inpaint: 'Inpaint zurücksetzen',
          txt2img: 'Txt2img zurücksetzen',
        },
        scheduler: 'Standardplaner',
        server: 'API-Server',
        state: 'Kundenstatus',
        darkMode: 'Dunkelmodus',
      },
      sourceFilter: {
        none: '',
        gaussian: '',
        noise: '',
        face: '',
        segment: '',
        mlsd: '',
        normal: '',
        hed: '',
        scribble: '',
        depth: '',
        canny: '',
        openpose: '',
      },
      tab: {
        blend: 'Mischung',
        img2img: '',
        inpaint: '',
        txt2txt: '',
        txt2img: '',
        upscale: 'Vergrößern',
      },
      tileOrder: {
        grid: 'Raster',
        spiral: 'Spiral',
      },
      tooltip: {
        delete: 'Löschen',
        next: 'Nächste',
        previous: 'Vorherige',
        retry: '',
        save: 'Speichern',
      },
      upscaleOrder: {
        'correction-both': 'Korrektur bei beiden',
        'correction-first': 'Korrektur zuerst',
        'correction-last': 'Korrektur zuletzt',
      },
      wildcard: '',
    },
  },
};
