/* eslint-disable camelcase */
/**
 * This is a machine translation and may have some mistakes.
 *
 * If you have a more accurate translation for any of these strings, please open an issue or pull request.
 */
export const I18N_STRINGS_FR = {
  fr: {
    translation: {
      admin: {
        restart: 'redémarrer les travailleurs',
      },
      convert: 'enregistrer et convertir',
      error: {
        image: {
          csam: '',
          memory: '',
          oom: '',
          unknown: '',
        },
        inpaint: {
          support: 'ce modèle peut ne pas prendre en charge l\'édition',
        },
      },
      experimental: {
        latent_symmetry: {
          label: '',
          gradient_start: '',
          gradient_end: '',
          line_of_symmetry: '',
        },
        prompt_editing: {
          add_suffix: '',
          filter: '',
          label: '',
          remove_tokens: '',
        },
      },
      extras: {
        add: 'ajouter',
        dest: 'nom de dossier',
        format: 'format de fichier',
        label: 'étiquette',
        model: 'modèle',
        name: 'nom',
        remove: 'retirer',
        scale: '',
        source: 'source',
        type: 'type',
      },
      generate: 'générer',
      profile: {
        add: 'ajouter un profil',
        saveName: 'enregistrer le nom du profil',
        saveProfile: 'enregistrer le profil',
        save: 'sauvegarder',
        saveCurrent: 'enregistrer le profil actuel',
        name: 'nom',
        cancel: 'annuler',
        load: 'profil de charge',
      },
      highresMethod: {
        bilinear: 'bilinéaire',
        lanczos: 'Lanczos',
        upscale: 'upscaler',
      },
      history: {
        empty: 'pas d\'histoire récente. appuyez sur générer pour créer une image.',
      },
      image: {
        thumbnail: 'vignette',
      },
      input: {
        image: {
          empty: 'veuillez sélectionner une image',
          mask: 'image de masque',
          source: 'image source',
        },
        list: {
          error: {
            specific: 'erreur: {{message}}',
            unknown: 'erreur inconnue',
          },
          idle: 'inactif',
          loading: 'chargement',
        },
        numeric: {
          error: {
            range: 'hors de portée',
          },
        },
      },
      loading: {
        cancel: 'Annuler',
        progress: '{{steps.current}} des {{steps.total}} pas, {{tiles.current}} des {{tiles.total}} tuiles, {{stages.current}} des {{stages.total}} étapes',
        queue: '{{current}} des {{total}} images en file d\'attente',
        server: 'Connexion au serveur...',
        unknown: 'nombreuses',
      },
      mask: {
        fill: {
          black: 'remplir de noir',
          white: 'remplir de blanc',
        },
        gray: {
          black: 'convertir le gris en noir',
          white: 'convertir le gris en blanc',
        },
        help: '',
        invert: 'Inverser les couleurs',
      },
      maskFilter: {
        'gaussian-multiply': 'multiplication gaussienne',
        'gaussian-screen': 'écran gaussien',
        'none': 'aucun',
      },
      modelType: {
        control: 'ControlNet',
        correction_one: 'modèle de correction',
        correction_other: 'modèles de correction',
        diffusion_one: 'modèle de diffusion',
        diffusion_other: 'modèles de diffusion',
        inversion: 'intégration',
        lora: 'LoRA',
        network_one: 'réseau supplémentaire',
        network_other: 'réseaux supplémentaires',
        source_one: 'autre source',
        source_other: 'd\'autres sources',
        upscaling_one: 'modèle de grossissement',
        upscaling_other: 'modèles de grossissement',
      },
      noiseSource: {
        'fill-edge': '',
        'fill-mask': '',
        'gaussian': '',
        'histogram': '',
        'normal': '',
        'uniform': '',
      },
      parameter: {
        batch: '',
        brush: {
          color: '',
          size: '',
          strength: '',
        },
        cfg: '',
        eta: '',
        fillColor: '',
        height: '',
        highres: {
          iterations: '',
          label: '',
          method: '',
          scale: '',
          steps: '',
          strength: '',
        },
        loopback: '',
        lpw: '',
        maskFilter: '',
        noiseSource: '',
        negativePrompt: '',
        newSeed: '',
        outpaint: {
          label: '',
          left: '',
          right: '',
          top: '',
          bottom: '',
        },
        overlap: '',
        pipeline: '',
        platform: '',
        prompt: '',
        scheduler: '',
        seed: '',
        size: '',
        sourceFilter: '',
        steps: '',
        strength: '',
        stride: '',
        tiled_vae: '',
        tiles: '',
        tileOrder: '',
        unet_overlap: '',
        unet_tile: '',
        upscale: {
          label: '',
          denoise: '',
          scale: '',
          order: '',
          outscale: '',
        },
        vae_overlap: '',
        vae_tile: '',
        width: '',
        correction: {
          label: '',
          strength: '',
          outscale: '',
        },
      },
      pipeline: {
        'none': '',
        'controlnet': '',
        'img2img': '',
        'img2img-sdxl': '',
        'inpaint': '',
        'inpaint-sdxl': '',
        'lpw': '',
        'panorama': '',
        'panorama-sdxl': '',
        'pix2pix': '',
        'txt2img': '',
        'txt2img-sdxl': '',
        'txt2txt': '',
        'upscale': '',
      },
      save: {
        image: '',
        metadata: '',
      },
      setting: {
        connectServer: '',
        history: {
          limit: '',
          width: '',
        },
        prompt: '',
        reset: {
          all: '',
          img2img: '',
          inpaint: '',
          txt2img: '',
        },
        scheduler: '',
        server: '',
        state: {
          label: '',
          load: '',
          save: '',
        },
        darkMode: 'Mode Sombre',
      },
      sourceFilter: {
        none: '',
        gaussian: '',
        noise: '',
        face: '',
        segment: '',
        mlsd: '',
        normal: '',
        hed: '',
        scribble: '',
        depth: '',
        canny: '',
        openpose: '',
      },
      tab: {
        blend: '',
        img2img: '',
        inpaint: '',
        models: '',
        settings: '',
        txt2txt: '',
        txt2img: '',
        upscale: '',
      },
      tileOrder: {
        grid: '',
        spiral: '',
      },
      tooltip: {
        delete: '',
        next: '',
        previous: '',
        retry: '',
        save: '',
      },
      upscaleOrder: {
        'correction-both': '',
        'correction-first': '',
        'correction-last': '',
      },
      wildcard: '',
    },
  },
};
