/* eslint-disable camelcase */
/**
 * This is a machine translation and may have some mistakes.
 *
 * If you have a more accurate translation for any of these strings, please open an issue or pull request.
 */
export const I18N_STRINGS_FR = {
  fr: {
    translation: {
      admin: {
        restart: '',
      },
      convert: '',
      error: {
        inpaint: {
          support: '',
        },
      },
      extras: {
        add: '',
        dest: '',
        format: '',
        label: '',
        model: '',
        name: '',
        remove: '',
        scale: '',
        source: '',
        type: '',
      },
      generate: 'générer',
      profile: {
        add: '',
        saveName: '',
        saveProfile: '',
        save: '',
        saveCurrent: '',
        name: '',
        cancel: '',
        load: '',
      },
      highresMethod: {
        bilinear: '',
        lanczos: '',
        upscale: '',
      },
      history: {
        empty: 'pas d\'histoire récente. appuyez sur générer pour créer une image.',
      },
      input: {
        image: {
          empty: 'veuillez sélectionner une image',
          mask: 'image de masque',
          source: 'image source',
        },
        list: {
          error: {
            specific: '',
            unknown: 'erreur inconnue',
          },
          idle: '',
          loading: '',
        },
        numeric: {
          error: {
            range: 'hors de portée',
          },
        },
        prompt: {
          tokens: '',
          error: {
            length: '',
          },
        },
      },
      loading: {
        cancel: 'Annuler',
        progress: '{{current}} des {{total}} étapes',
        server: 'Connexion au serveur...',
        unknown: 'nombreuses',
      },
      mask: {
        fill: {
          black: 'remplir de noir',
          white: 'remplir de blanc',
        },
        gray: {
          black: 'convertir le gris en noir',
          white: 'convertir le gris en blanc',
        },
        help: '',
        invert: 'Inverser les couleurs',
      },
      maskFilter: {
        'gaussian-multiply': '',
        'gaussian-screen': '',
        'none': '',
      },
      modelType: {
        control: '',
        correction_one: 'modèle de correction',
        correction_other: '',
        diffusion_one: 'modèle de diffusion',
        diffusion_other: '',
        inversion: '',
        lora: '',
        network_one: '',
        network_other: '',
        source_one: '',
        source_other: '',
        upscaling_one: 'modèle de grossissement',
        upscaling_other: '',
      },
      noiseSource: {
        'fill-edge': '',
        'fill-mask': '',
        'gaussian': '',
        'histogram': '',
        'normal': '',
        'uniform': '',
      },
      parameter: {
        batch: '',
        brush: {
          color: '',
          size: '',
          strength: '',
        },
        cfg: '',
        eta: '',
        fillColor: '',
        height: '',
        highres: {
          iterations: '',
          label: '',
          method: '',
          scale: '',
          steps: '',
          strength: '',
        },
        loopback: '',
        lpw: '',
        maskFilter: '',
        noiseSource: '',
        negativePrompt: '',
        newSeed: '',
        outpaint: {
          label: '',
          left: '',
          right: '',
          top: '',
          bottom: '',
        },
        overlap: '',
        pipeline: '',
        platform: '',
        prompt: '',
        scheduler: '',
        seed: '',
        size: '',
        sourceFilter: '',
        steps: '',
        strength: '',
        stride: '',
        tiledVAE: '',
        tiles: '',
        tileOrder: '',
        upscale: {
          label: '',
          denoise: '',
          scale: '',
          order: '',
          outscale: '',
        },
        width: '',
        correction: {
          label: '',
          strength: '',
          outscale: '',
        },
      },
      pipeline: {
        none: '',
        controlnet: '',
        img2img: '',
        inpaint: '',
        lpw: '',
        panorama: '',
        pix2pix: '',
        txt2img: '',
        txt2txt: '',
        upscale: '',
      },
      setting: {
        connectServer: '',
        history: '',
        loadState: '',
        prompt: '',
        reset: {
          all: '',
          img2img: '',
          inpaint: '',
          txt2img: '',
        },
        scheduler: '',
        server: '',
        state: '',
        darkMode: 'Mode Sombre',
      },
      sourceFilter: {
        none: '',
        gaussian: '',
        noise: '',
        face: '',
        segment: '',
        mlsd: '',
        normal: '',
        hed: '',
        scribble: '',
        depth: '',
        canny: '',
        openpose: '',
      },
      tab: {
        blend: '',
        img2img: '',
        inpaint: '',
        txt2txt: '',
        txt2img: '',
        upscale: '',
      },
      tileOrder: {
        grid: '',
        spiral: '',
      },
      tooltip: {
        delete: '',
        next: '',
        previous: '',
        retry: '',
        save: '',
      },
      upscaleOrder: {
        'correction-both': '',
        'correction-first': '',
        'correction-last': '',
      },
    },
  },
};
