FROM docker.io/python:3.10-alpine

RUN apk add --update cmake \
 && rm -rf /var/cache/apk/*

WORKDIR /onnx-web

RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

COPY requirements.txt /onnx-web/requirements.txt

RUN pip install -r requirements.txt

COPY onnx_web/ /onnx-web/onnx_web/

ENTRYPOINT [ "flask", "--app=onnx_web.serve", "run", "--host=0.0.0.0" ]
