FROM docker.io/python:3.10-alpine

WORKDIR /onnx-web

COPY requirements.txt /onnx-web/requirements.txt
COPY serve.py /onnx-web/serve.py

RUN pip install -r requirements.txt

# RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.2

ENTRYPOINT [ "flask", "--app=serve", "run", "--host=0.0.0.0" ]
